name = "SeqLogo"
uuid = "9b242ebb-1f45-4793-8beb-b444653b6215"
authors = ["Shane Kuei-Hsien Chu (skchu@wustl.edu)"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
